server:
  port: 8762
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    healthcheck:
      enabled: true   # 使用Edgware.SR4版本的spring cloud必须要加的参数，不然会报错

spring:
  application:
    name: member
  #redis连接信息
  #  redis:
  #    host: 192.168.110.163
  #    password: 123456
  #    port: 6379
  #    pool:
  #      max-idle: 100
  #      min-idle: 1
  #      max-active: 1000
  #      max-wait: -1
  #数据库连接信息
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/mj-mall-member?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
